#!/usr/bin/env bash
# Setup KofamScan database and config
# Run this after activating the kofamscan conda env: conda activate kofamscan
# Usage: ./setup_kofamscan.sh [kofamscan_dir]

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
KOFAM_DIR="${1:-$SCRIPT_DIR}"
DB_DIR="$KOFAM_DIR/db"
BIN_DIR="$KOFAM_DIR/kofam_scan-1.3.0"

# Resolve paths
KOFAM_DIR="$(cd "$KOFAM_DIR" && pwd)"
DB_DIR="$KOFAM_DIR/db"
BIN_DIR="$KOFAM_DIR/kofam_scan-1.3.0"

KOFAMSCAN_URL="https://www.genome.jp/ftp/tools/kofam_scan/kofam_scan-1.3.0.tar.gz"

echo "Setting up KofamScan in $KOFAM_DIR"

# Download and extract kofam_scan if not present
if [[ ! -f "$BIN_DIR/exec_annotation" ]]; then
    echo "Downloading kofam_scan-1.3.0..."
    wget -q "$KOFAMSCAN_URL" -O "$KOFAM_DIR/kofam_scan-1.3.0.tar.gz"
    tar xzf "$KOFAM_DIR/kofam_scan-1.3.0.tar.gz" -C "$KOFAM_DIR"
    rm -f "$KOFAM_DIR/kofam_scan-1.3.0.tar.gz"
    echo "Extracted to $BIN_DIR"
else
    echo "kofam_scan-1.3.0 already exists"
fi

# Download KOfam database
mkdir -p "$DB_DIR"
cd "$DB_DIR"

if [[ ! -f ko_list ]]; then
    echo "Downloading ko_list..."
    wget -q ftp://ftp.genome.jp/pub/db/kofam/ko_list.gz
    gunzip ko_list.gz
else
    echo "ko_list already exists"
fi

if [[ ! -d profiles ]] || [[ -z "$(ls -A profiles 2>/dev/null)" ]]; then
    echo "Downloading profiles..."
    wget -q ftp://ftp.genome.jp/pub/db/kofam/profiles.tar.gz
    tar xzf profiles.tar.gz
    rm -f profiles.tar.gz
else
    echo "profiles directory already exists"
fi

# Create config.yml
HMMSEARCH="$(which hmmsearch)"
PARALLEL="$(which parallel)"

if [[ -z "$HMMSEARCH" ]] || [[ -z "$PARALLEL" ]]; then
    echo "Error: hmmsearch or parallel not in PATH. Activate the kofamscan conda env first:"
    echo "  conda activate kofamscan"
    exit 1
fi

CONFIG="$BIN_DIR/config.yml"
NCPU=$(nproc 2>/dev/null || echo 8)
cat > "$CONFIG" << EOF
# KofamScan config - generated by setup_kofamscan.sh
profile: $DB_DIR/profiles
ko_list: $DB_DIR/ko_list
hmmsearch: $HMMSEARCH
parallel: $PARALLEL
cpu: $NCPU
EOF

echo "Config written to $CONFIG"
echo "Setup complete. Run: ./run_kofamscan.sh"
